services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agileflow-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: API/Dockerfile
    container_name: agileflow-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=AgileFlow;User Id=sa;Password=Your_password123;TrustServerCertificate=true;
      - Jwt__Issuer=AgileFlow
      - Jwt__Audience=AgileFlow.Client
      - Jwt__Key=ReplaceWithStrongKey
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agileflow-web
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  sql_data:
